### ISSUE TITLE
-100,000 is too damn high!

### ISSUE THREAD

**Issue by iankronquist** [ElijahCaine/huRandom#9]
It should say that the number is too low.
https://github.com/ElijahCaine/huRandom/blob/develop/huRandom/huRandom.py#L72

**Comment by pop** [comment]
That number is 1,000,000 not 100,000. Is that still a problem @iankronquist ?

**Comment by iankronquist** [comment]
`-20,000,000 is too high! Please submit a number above -1,000,000.`
My number is too _low_.

**Comment by pop** [comment]
Resolved with the most recent commit.
